#! /usr/bin/php
<?php

// checks all language in current directory
// use "checklang --repair" to add missing variables

//error_reporting(0);

$eng_array = array();
$comp_array = array();

function getEnglishLangFile()
{
	global $eng_array;

	// check whether both arguments are files
	if (!is_file("ilias_en.lang"))
	{
		die ($file1." is not a file.\n");
	}

	// read file 1
	if ($handle = fopen("ilias_en.lang", "r"))
	{
		while (false !== ($line = fgets($handle, 4096)))
		{
			$arr = explode("#:#", $line);
			if (isset($arr[1]) && $arr[1] != "")
			{
				//$arr2 = substr($arr[2], 0, strlen($arr[2])-1);
				$arr2 = str_replace(array("\n", "\r"), array("", ""), $arr[2]);
				$eng_array[$arr[0]."#:#".$arr[1]] =
					$arr2;
			}
		}
		fclose($handle);
	}
}

function compareFile($a_file)
{
	global $comp_array, $output_file, $eng_array, $argv;

	// output all variables only in file 1
	echo "Deprecated in $a_file\n";
	echo "===================================\n";

	$comp_array = array();
	
	// check whether both arguments are files
	if (!is_file($a_file))
	{
		die ($a_file." is not a file.\n");
	}

	// get output file
	if (isset($argv[1]) && trim($argv[1] == "--repair"))
	{
		$output_file = fopen($a_file.".new", "w");
	}

	// read file
	if ($handle = fopen($a_file, "r"))
	{
		while (false !== ($line = fgets($handle, 4096)))
		{
			$arr = explode("#:#", $line);
			if(!isset($arr[1]))
			{
				$arr[1] = "";
			}

			if ($arr[1] != "")
			{
				$comp_array[$arr[0]."#:#".$arr[1]] =
					substr($arr[2], 0, strlen($arr[2])-1);
			}
			
			// write line by line to new output file
			if ($arr[1] == "" || isset($eng_array[$arr[0]."#:#".$arr[1]]))
			{
				if (isset($argv[1]) && trim($argv[1] == "--repair"))
				{
					if (substr($line, strlen($line)-1) != "\n")
					{
						$line.= "\n";
					}
					if ($line != "\n")
					{
						fwrite($output_file, $line);
					}
				}
			}
			else
			{
				echo $line;
			}
		}
		fclose($handle);
	}
	
	outputStatus($a_file);

	// close output file
	if (isset($argv[1]) && trim($argv[1] == "--repair"))
	{
		fclose($output_file);
		rename($a_file.".new", $a_file);
	}
	
}

function outputStatus($a_file)
{
	global $eng_array, $comp_array, $argv, $output_file;
	
	// output all variables only in file 1
	echo "Missing in $a_file\n";
	echo "===================================\n";

	foreach($eng_array as $key => $val)
	{
		if (!isset($comp_array[$key]))
		{
			echo $key."#:#".$val."###\n";
			
			// Write missing line to end of output file
			if (isset($argv[1]) && trim($argv[1] == "--repair"))
			{
				$newline = $key."#:#".$val;
				if (!is_int(strpos($val, "###")))
				{
					$newline.= "###".date("d m Y")." new variable";
				}
				fwrite($output_file, $newline."\n");
			}
		}
	}

	echo "\n";
}
echo("Read english lang file...");
getEnglishLangFile();

if ($handle = opendir("."))
{
	while (false !== ($file = readdir($handle)))
	{
		if ($file != "." && $file != ".." && $file != "ilias_en.lang")
		{
			if (preg_match("/^ilias_..\.lang$/", $file))
			{
				//echo("Check File: " . $file);
				compareFile($file);
			}
		}
	}
	closedir($handle);
}

?>
